const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const base=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();let report=JSON.parse(fs.readFileSync(path.join(base,'ai-engine/reports/layers_latest.json'))),fallback=false;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.WebSocket=class{constructor(){window.testSocket=this;this.readyState=1;setTimeout(()=>this.onopen?.(),1)}emit(d){this.onmessage?.({data:JSON.stringify({data:d})})}}});
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='raw.githubusercontent.com'&&fallback){await route.fulfill({status:503,body:'unavailable'});return}if(u.pathname.endsWith('layers_latest.json')){await route.fulfill({json:report});return}if(u.pathname.endsWith('paper_live.json')){await route.fulfill({json:JSON.parse(fs.readFileSync(path.join(base,'ai-engine/reports/paper_live.json')))});return}if(u.pathname==='/ai-dashboard/'){await route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(base,'ai-dashboard/index.html'))});return}if(u.pathname.endsWith('.js')||u.pathname.endsWith('.css')){await route.fulfill({contentType:u.pathname.endsWith('.js')?'text/javascript':'text/css',body:fs.readFileSync(path.join(base,'ai-dashboard',path.basename(u.pathname)))});return}await route.fulfill({contentType:'text/html',body:'<p>Chart fixture</p>'})});
 report.live_rest_available=true;report.collection.market['SPYUSDT/last'].source='rest';
 await page.goto('http://layers.test/ai-dashboard/');await page.waitForFunction(()=>document.querySelectorAll('[data-bars]').length===4);assert.equal(await page.locator('#groups tr').count(),5);assert.equal(await page.locator('#matrixPanel').count(),0);
 for(const [w,h,name] of [[1440,1000,'desktop'],[390,844,'mobile'],[844,390,'landscape']]){await page.setViewportSize({width:w,height:h});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-bars="8"]').click();assert((await page.locator('#selectedTitle').innerText()).includes('120 phút'));await page.screenshot({path:path.join(require('os').tmpdir(),`layers-${name}.png`)});}
 await page.evaluate(()=>testSocket.emit({e:'aggTrade',p:'777.1234'}));assert.equal(await page.locator('#livePrice').innerText(),'777.1234');
 report={...report,data_as_of:Date.now()-3*3600000,stale:false};await page.locator('#refresh').click();await page.waitForFunction(()=>document.getElementById('dataStatus').textContent.includes('DỮ LIỆU CŨ'));assert((await page.locator('#decision').innerText()).startsWith('WAIT'));
 report={...report,data_as_of:Date.now(),live_rest_available:false};await page.locator('#refresh').click();await page.waitForFunction(()=>document.getElementById('dataStatus').textContent.includes('REST runner bị chặn'));assert((await page.locator('#decision').innerText()).startsWith('WAIT'));
 fallback=true;await page.locator('#refresh').click();await page.waitForFunction(()=>!document.getElementById('refresh').disabled);
 assert.deepEqual(errors,[]);console.log('4 horizons, 5 groups, live price, stale WAIT, raw-to-Pages fallback, desktop/mobile/landscape, no JS errors: passed');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
