const assert=require('node:assert/strict');
const M=require('./matrix-v2.js'),step=900000;
const data=Array.from({length:401},(_,i)=>({time:i*step,closeTime:(i+1)*step-1,last:100+i,strength:1}));
const asOf=data[300].closeTime+1,d=M.defs[0];
const before=M.stats(data,d,asOf,1);
const revised=data.map((r,i)=>i>300?{...r,last:1e6-i}:r);
assert.deepEqual(M.stats(revised,d,asOf,1),before,'Future outcomes must not change earlier confidence');
assert.equal(before.n,75,'Non-overlapping 4-bar samples');
assert.equal(M.stats(data,d,data[4].closeTime,1).n,0,'Unclosed target excluded');
assert.equal(M.stats(data,d,data[4].closeTime+1,1).n,1);
assert.equal(M.phase(.15),'BULL');assert.equal(M.phase(-.15),'BEAR');assert.equal(M.phase(.149),'NEUTRAL');
assert.equal(M.score(.1,{confidence:1}),0);
assert.equal(M.score(-1,{confidence:1}),-100);
assert.equal(M.score(1,{confidence:0}),25);
assert.equal(M.value({topLS:1,v2Available:{topLS:false}},M.defs[2]),NaN);
assert.equal(M.value({topLS:null},M.defs[2]),NaN);
const result=M.evaluate(data,{strength:1},asOf);
assert.equal(result.coverage,1);assert.equal(result.composite,result.factors[0].score/12);
const flat=data.map(r=>({...r,last:100}));
assert.equal(M.stats(flat,d,asOf,1).hit,0);assert.equal(M.stats(flat,d,asOf,1).edge,0);assert.equal(M.stats(flat,d,asOf,1).bps,-4);
assert.equal(M.stats(flat,d,asOf,1).confidence,0);
const gaps=data.map((r,i)=>({...r,time:r.time+(i>=4?step:0)}));
assert.ok(M.stats(gaps,d,asOf,1).n<before.n,'Missing M15 bars excluded');
assert.equal(M.value({oiZ:2,oiDelta:-10,r4:.01},M.defs[6]),-Math.tanh(1));
console.log('Matrix V2: causal cutoff, closed labels, gaps, phase boundaries, missing data, fixed denominator, fees and OI passed.');
