const $=id=>document.getElementById(id);
const fileEl=$('file'),drop=$('drop'),rowsEl=$('rows'),thead=$('thead'),stats=$('stats'),msg=$('msg'),dateEl=$('date'),daysEl=$('days'),send=$('send'),exportBtn=$('export'),apiUrl=$('apiUrl'),apiState=$('apiState'),result=$('result'),connBadge=$('connBadge');
const HEADERS=['STT','HỌ TÊN (*)','NGÀY SINH (*)','GIỚI TÍNH (*)','QUỐC TỊCH (*)','LOẠI GIẤY TỜ (*)','TÊN GIẤY TỜ','SỐ GIẤY TỜ (*)','SỐ ĐIỆN THOẠI','NƠI CƯ TRÚ HIỆN NAY','TỈNH/ THÀNH PHỐ','PHƯỜNG/ XÃ/ ĐẶC KHU','ĐỊA CHỈ CHI TIẾT','NGÀY ĐẾN (*)','NGÀY ĐI DỰ KIẾN (*)','SỐ PHÒNG/ KHOA','LÝ DO CƯ TRÚ (*)','NHẬP LÝ DO','GHI CHÚ'];
const OPTIONS={gender:['F - Nữ','M - Nam'],nation:['VNM - Viet Nam'],doc:['1 - Thẻ CCCD','2 - Thẻ CMND','3 - Giấy phép lái xe','4 - Hộ chiếu','5 - Giấy khai sinh','6 - Thẻ BHYT','7 - Thông báo số định danh cá nhân'],residence:['1 - Thường trú','2 - Tạm trú','3 - Khác'],reason:['1 - Du lịch','2 - Công tác','3 - Học tập','4 - Thăm viếng','5 - Hội nghị','6 - Thăm thân','7 - Từ thiện','18 - Chữa bệnh','19 - Khác']};
let data=[],apiOnline=false;
dateEl.value=new Date().toISOString().slice(0,10);apiUrl.value=localStorage.getItem('kbtt_api_url')||'http://127.0.0.1:8765';
apiUrl.onchange=()=>{localStorage.setItem('kbtt_api_url',apiUrl.value.trim());apiOnline=false;paintConn('Chưa kiểm tra','off')};
fileEl.onchange=e=>e.target.files[0]&&readFile(e.target.files[0]);drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])readFile(e.dataTransfer.files[0])};
$('checkApi').onclick=checkApi;$('demo').onclick=demo;exportBtn.onclick=exportXlsx;send.onclick=sendApi;
function demo(){data=[row({stt:1,ten:'BÙI THỊ THU',ns:'24/04/1984',gt:'F - Nữ',qt:'VNM - Viet Nam',loai:'6 - Thẻ BHYT',so:'GD4251720204306',tinh:'217 - Phú Thọ',xa:'217905047 - Xã Cao Dương',dc:'Thôn Yên Lịch',phong:'BUỒNG BỆNH 207',lydo:'18 - Chữa bệnh'}),row({stt:2,ten:'ĐINH HỒNG HẢI',ns:'22/05/1956',gt:'M - Nam',qt:'VNM - Viet Nam',loai:'6 - Thẻ BHYT',so:'CB2251720142769',tinh:'217 - Phú Thọ',xa:'217904894 - Phường Kỳ Sơn',phong:'BUỒNG BỆNH 209',lydo:'18 - Chữa bệnh'})];render()}
function row(o={}){return {stt:o.stt||'',ten:o.ten||'',ns:o.ns||'',gt:o.gt||'M - Nam',qt:o.qt||'VNM - Viet Nam',loai:o.loai||'6 - Thẻ BHYT',tengiay:o.tengiay||'',so:o.so||'',dt:o.dt||'',noicutru:o.noicutru||'',tinh:o.tinh||'217 - Phú Thọ',xa:o.xa||'',dc:o.dc||'',den:o.den||dateEl.value,di:o.di||leave(dateEl.value),phong:o.phong||'',lydo:o.lydo||'18 - Chữa bệnh',nhaplydo:o.nhaplydo||'',ghichu:o.ghichu||''}}
function findHeader(a){for(let i=0;i<Math.min(a.length,20);i++){const s=a[i].map(v=>String(v).trim().toUpperCase());if(s.some(v=>v.includes('HỌ TÊN'))&&s.some(v=>v.includes('SỐ GIẤY TỜ')))return i}return -1}
function find(h,terms){for(const term of terms){const i=h.findIndex(v=>String(v).trim().toUpperCase()===term.toUpperCase());if(i>=0)return i}return -1}
function readFile(file){msg.textContent='Đang đọc '+file.name+'...';const fr=new FileReader();fr.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array',cellDates:false});const ws=wb.Sheets[wb.SheetNames[0]],a=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});const hi=findHeader(a);if(hi<0)throw Error('Không tìm thấy dòng tiêu đề chuẩn KBTT');const h=a[hi].map(String);const I={ten:find(h,['HỌ TÊN (*)','HỌ TÊN']),ns:find(h,['NGÀY SINH (*)','NGÀY SINH']),gt:find(h,['GIỚI TÍNH (*)','GIỚI TÍNH']),qt:find(h,['QUỐC TỊCH (*)','QUỐC TỊCH']),loai:find(h,['LOẠI GIẤY TỜ (*)','LOẠI GIẤY TỜ']),tengiay:find(h,['TÊN GIẤY TỜ']),so:find(h,['SỐ GIẤY TỜ (*)','SỐ GIẤY TỜ']),dt:find(h,['SỐ ĐIỆN THOẠI']),noicutru:find(h,['NƠI CƯ TRÚ HIỆN NAY']),tinh:find(h,['TỈNH/ THÀNH PHỐ','TỈNH/THÀNH PHỐ']),xa:find(h,['PHƯỜNG/ XÃ/ ĐẶC KHU','PHƯỜNG/XÃ/ĐẶC KHU']),dc:find(h,['ĐỊA CHỈ CHI TIẾT']),den:find(h,['NGÀY ĐẾN (*)','NGÀY ĐẾN']),di:find(h,['NGÀY ĐI DỰ KIẾN (*)','NGÀY ĐI DỰ KIẾN']),phong:find(h,['SỐ PHÒNG/ KHOA','SỐ PHÒNG/KHOA']),lydo:find(h,['LÝ DO CƯ TRÚ (*)','LÝ DO CƯ TRÚ']),nhaplydo:find(h,['NHẬP LÝ DO']),ghichu:find(h,['GHI CHÚ']),stt:find(h,['STT'])};data=a.slice(hi+1).filter(r=>r.some(v=>String(v).trim())&&!String(r[I.ten]||'').startsWith('<')).map((r,n)=>row({stt:r[I.stt]||n+1,ten:r[I.ten],ns:r[I.ns],gt:r[I.gt],qt:r[I.qt],loai:r[I.loai],tengiay:r[I.tengiay],so:r[I.so],dt:r[I.dt],noicutru:r[I.noicutru],tinh:r[I.tinh],xa:r[I.xa],dc:r[I.dc],den:r[I.den],di:r[I.di],phong:r[I.phong],lydo:r[I.lydo],nhaplydo:r[I.nhaplydo],ghichu:r[I.ghichu]}));render();msg.textContent='Đã đọc '+data.length+' bệnh nhân theo đúng mẫu 19 cột KBTT.'}catch(err){msg.textContent='Không đọc được file: '+err.message}};fr.readAsArrayBuffer(file)}
function valid(r){return !!(r.ten&&r.ns&&r.gt&&r.qt&&r.loai&&r.so&&r.tinh&&r.xa&&r.den&&r.di&&r.phong&&r.lydo)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function input(k,i,wide=false){return '<input class="cell-input '+(wide?'wide ':'')+(data[i][k]?'':'need')+'" data-k="'+k+'" data-i="'+i+'" value="'+esc(data[i][k])+'">'}
function select(k,i,opts){return '<select class="cell-select '+(data[i][k]?'':'need')+'" data-k="'+k+'" data-i="'+i+'">'+opts.map(o=>'<option '+(data[i][k]===o?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>'}
function render(){thead.innerHTML='<tr>'+HEADERS.map(h=>'<th>'+h+'</th>').join('')+'<th>TRẠNG THÁI</th></tr>';rowsEl.innerHTML='';let good=0;data.forEach((r,i)=>{if(valid(r))good++;const cells=[esc(r.stt),input('ten',i,true),input('ns',i),select('gt',i,OPTIONS.gender),select('qt',i,OPTIONS.nation),select('loai',i,OPTIONS.doc),input('tengiay',i),input('so',i),input('dt',i),select('noicutru',i,OPTIONS.residence),input('tinh',i,true),input('xa',i,true),input('dc',i,true),input('den',i),input('di',i),input('phong',i,true),select('lydo',i,OPTIONS.reason),input('nhaplydo',i),input('ghichu',i),'<span class="'+(valid(r)?'ok':'bad')+'">'+(valid(r)?'✓ Sẵn sàng':'⚠ Cần bổ sung')+'</span>'];const tr=document.createElement('tr');tr.innerHTML=cells.map(x=>'<td>'+x+'</td>').join('');rowsEl.appendChild(tr)});document.querySelectorAll('[data-k]').forEach(el=>el.oninput=el.onchange=()=>{data[+el.dataset.i][el.dataset.k]=el.value;renderKeep(+el.dataset.i)});stats.textContent=data.length+' bệnh nhân · '+good+' sẵn sàng · '+(data.length-good)+' cần bổ sung';send.disabled=!data.length||good!==data.length;exportBtn.disabled=!data.length;apiState.textContent=apiOnline?'Python backend đã kết nối.':'Chưa kết nối Python backend.'}
function renderKeep(i){const y=scrollY;render();scrollTo(0,y)}
function leave(s){const d=new Date(s+'T00:00:00');if(isNaN(d))return'';d.setDate(d.getDate()+Number(daysEl.value||7));return d.toLocaleDateString('vi-VN')}
dateEl.onchange=()=>{data.forEach(r=>{if(!r.den)r.den=dateEl.value;if(!r.di)r.di=leave(dateEl.value)});render()};daysEl.oninput=()=>{data.forEach(r=>{if(r.den)r.di=leave(r.den)});render()};
function exportXlsx(){if(data.some(r=>!valid(r))){alert('Còn dữ liệu bắt buộc chưa đủ. Hãy sửa các ô màu vàng trước khi xuất.');return}const out=[HEADERS];data.forEach(r=>out.push([r.stt,r.ten,r.ns,r.gt,r.qt,r.loai,r.tengiay,r.so,r.dt,r.noicutru,r.tinh,r.xa,r.dc,r.den,r.di,r.phong,r.lydo,r.nhaplydo,r.ghichu]));const ws=XLSX.utils.aoa_to_sheet(out);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'DS_KHACH_VIET_NAM_LUU_TRU');XLSX.writeFile(wb,'tblt_vn_import_kbtt.xlsx')}
async function checkApi(){paintConn('Đang kiểm tra...','off');try{const r=await fetch(base()+'/api/health');if(!r.ok)throw Error('HTTP '+r.status);apiOnline=true;paintConn('Python đã kết nối','ok');apiState.textContent='Backend Python trên máy bệnh viện đang hoạt động.'}catch(e){apiOnline=false;paintConn('Chưa kết nối','bad');apiState.textContent='Chưa có Python backend. Bạn vẫn có thể chuẩn hóa và xuất Excel.'}}
function paintConn(t,c){connBadge.textContent=t;connBadge.className='pill '+c}function base(){return apiUrl.value.trim().replace(/\/$/,'')}
async function sendApi(){if(data.some(r=>!valid(r))){alert('Còn dữ liệu bắt buộc chưa đủ.');return}result.className='result';result.textContent='Đang gửi '+data.length+' bệnh nhân...';try{const r=await fetch(base()+'/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patients:data})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||j.message||'HTTP '+r.status);result.className='result ok';result.textContent=j.message||'Đã gửi thành công.'}catch(e){result.className='result bad';result.textContent='Không gửi được: '+e.message}}
render();