const fileEl=document.getElementById('file'),drop=document.getElementById('drop'),rowsEl=document.getElementById('rows'),stats=document.getElementById('stats'),msg=document.getElementById('msg'),dateEl=document.getElementById('date'),daysEl=document.getElementById('days'),send=document.getElementById('send');
let data=[];
dateEl.value=new Date().toISOString().slice(0,10);
fileEl.onchange=e=>e.target.files[0]&&readFile(e.target.files[0]);
drop.ondragover=e=>{e.preventDefault()}; drop.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])readFile(e.dataTransfer.files[0])};
document.getElementById('demo').onclick=()=>{data=[
{ten:'Nguyễn Văn A',ns:'01/01/1980',giayto:'123456789012',gt:'Nam',dc:'Hà Nội -- Phường Cầu Giấy',phong:'Phòng 01',loai:'1'},
{ten:'Trần Thị B',ns:'02/02/1990',giayto:'',gt:'Nữ',dc:'Hòa Bình -- Phường Tân Hòa',phong:'Phòng 02',loai:'1'},
{ten:'Lê Văn C',ns:'03/03/1975',giayto:'',gt:'Nam',dc:'Hòa Bình -- Phường Tân Hòa',phong:'Phòng 03',loai:'1'}];render()};
function readFile(file){msg.textContent='Đang đọc '+file.name+'...';const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array',cellDates:true});const a=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});data=parseRows(a);render()}catch(err){msg.textContent='Không đọc được file: '+err.message}};r.readAsArrayBuffer(file)}
function find(h,n){for(const x of n){const i=h.findIndex(v=>String(v).trim().toLowerCase()===x.toLowerCase());if(i>=0)return i}return-1}
function parseRows(a){if(!a.length)return[];const h=a[0].map(String),t=find(h,['Họ tên','hoTen','hoten']),ns=find(h,['ngaysinh','Ngày sinh']),g=find(h,['Số thẻ','soGiayTo','CCCD']),gt=find(h,['GT','Giới tính']),dc=find(h,['Địa chỉ','diachi']),p=find(h,['Phòng','phong']);if(t<0)return a.filter(r=>r.some(Boolean)).slice(0,500).map(r=>({ten:r[1]||'',ns:r[2]||'',giayto:r[17]||'',gt:r[7]||'',dc:r[15]||'',phong:r[16]||'',loai:'1'}));return a.slice(1).filter(r=>r[t]).map(r=>({ten:r[t],ns:r[ns],giayto:r[g],gt:r[gt],dc:r[dc],phong:r[p],loai:'1'}))}
function valid(r){const s=String(r.giayto||'').replace(/\\s/g,'');if(!s||!r.ten||!r.ns||!r.gt||!r.phong)return false;if(r.loai==='1')return /^\\d{12}$/.test(s);if(r.loai==='2')return /^\\d{9}$|^\\d{12}$/.test(s);if(r.loai==='4')return s.length<=10;return s.length<=20}
function render(){rowsEl.innerHTML='';let good=0;data.forEach((r,i)=>{if(valid(r))good++;const tr=document.createElement('tr');tr.innerHTML='<td>'+(i+1)+'</td><td>'+esc(r.ten)+'</td><td>'+esc(r.ns)+'</td><td class="doccell"><select class="doctype" data-i="'+i+'"><option value="1" '+(r.loai==='1'?'selected':'')+'>CCCD</option><option value="2" '+(r.loai==='2'?'selected':'')+'>CMND</option><option value="6" '+(r.loai==='6'?'selected':'')+'>BHYT</option><option value="4" '+(r.loai==='4'?'selected':'')+'>Hộ chiếu</option></select><input class="docinput '+(r.giayto?'':'need')+'" data-i="'+i+'" value="'+esc(r.giayto)+'" placeholder="Nhập số giấy tờ"></td><td>'+esc(r.gt)+'</td><td>'+esc(r.dc)+'</td><td>'+esc(dateEl.value)+'</td><td>'+esc(leave(dateEl.value))+'</td><td>'+esc(r.phong)+'</td><td class="'+(valid(r)?'ok':'bad')+'">'+(valid(r)?'✓ Sẵn sàng':'⚠ Cần bổ sung/sửa')+'</td>';rowsEl.appendChild(tr)});document.querySelectorAll('.docinput').forEach(x=>x.oninput=()=>{data[+x.dataset.i].giayto=x.value.replace(/\\s/g,'');renderKeep(+x.dataset.i)});document.querySelectorAll('.doctype').forEach(x=>x.onchange=()=>{data[+x.dataset.i].loai=x.value;render()});stats.textContent=data.length+' bệnh nhân · '+good+' sẵn sàng · '+(data.length-good)+' cần sửa';msg.textContent=data.length?'Sửa trực tiếp ngay trên dòng bệnh nhân. Khi tất cả đều hợp lệ, nút gửi sẽ được mở.':'Chưa có dữ liệu.';send.disabled=!data.length||good!==data.length}
function renderKeep(i){render();const x=document.querySelector('.docinput[data-i="'+i+'"]');if(x){x.focus();x.setSelectionRange(x.value.length,x.value.length)}}
function leave(s){const d=new Date(s+'T00:00:00');if(isNaN(d))return'';d.setDate(d.getDate()+Number(daysEl.value||7));return d.toLocaleDateString('vi-VN')}
dateEl.onchange=daysEl.oninput=render;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
send.onclick=()=>{if(data.some(r=>!valid(r))){alert('Còn bệnh nhân chưa hợp lệ. Hãy sửa trực tiếp trên bảng.');return}alert('Đã kiểm tra: tất cả bệnh nhân hợp lệ. Bước kế tiếp là nối nút này với backend Python kbtt_api.py để gửi thật KBTT.')};